const RecordActionTypes = {
  ERROR: 'ERROR',
  LOADING: 'LOADING',
  CHANGE_TERM: 'CHANGE_TERM',
  CHANGE_PAGE: 'CHANGE_PAGE',
  LOAD_RECORDS_SUCCESS: 'LOAD_RECORDS_SUCCESS',
  LOAD_RECORDS_FAILURE: 'LOAD_RECORDS_FAILURE',
};

export default RecordActionTypes;
